export const PERFORM_LOGIN_ACTION = 'PERFORM_LOGIN';
export const PERFORM_SIGNUP_ACTION = 'PERFORM_SIGNUP';
export const LOGIN_ACTION_SUCCESS = 'SUCCESSFUL_LOGIN';
export const LOGIN_ACTION_FAIL ='UNSUCCESSFUL_LOGIN';
export const LOGOUT_ACTION = 'PERFORM_LOGOUT';